services:
  postgresDb:
    image: postgres:latest
    container_name: postgresDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: suivi_commande_dev
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgresDb

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "4010:4010"
    env_file: ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-dev
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend-dev:/src
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
