global:
  scrape_interval: 15s

scrape_configs:
   - job_name: nestjs-metrics
     scrape_interval: 15s
     scrape_timeout: 10s
     metrics_path: /metrics
     static_configs:
      - targets:
          - 'prometheus:9090'
          - 'backend:4010'