/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as GuestVerifyEmailTokenRouteImport } from './routes/_guest/verify-email/$token'
import { Route as GuestloginLoginRouteImport } from './routes/_guest/(login)/login'
import { Route as AuthenticatedPilotagesUsersIndexRouteImport } from './routes/_authenticated/pilotages/users/index'
import { Route as AuthenticatedPilotagesTestTableIndexRouteImport } from './routes/_authenticated/pilotages/test-table/index'
import { Route as AuthenticatedPilotagesTeamsIndexRouteImport } from './routes/_authenticated/pilotages/teams/index'
import { Route as AuthenticatedPilotagesSubdivisionClientsIndexRouteImport } from './routes/_authenticated/pilotages/subdivision-clients/index'
import { Route as AuthenticatedPilotagesServicesIndexRouteImport } from './routes/_authenticated/pilotages/services/index'
import { Route as AuthenticatedPilotagesServiceCategoriesIndexRouteImport } from './routes/_authenticated/pilotages/service-categories/index'
import { Route as AuthenticatedPilotagesSectorsIndexRouteImport } from './routes/_authenticated/pilotages/sectors/index'
import { Route as AuthenticatedPilotagesRequisitionTypesIndexRouteImport } from './routes/_authenticated/pilotages/requisition-types/index'
import { Route as AuthenticatedPilotagesRequestTypesIndexRouteImport } from './routes/_authenticated/pilotages/request-types/index'
import { Route as AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRouteImport } from './routes/_authenticated/pilotages/request-type-service-categories/index'
import { Route as AuthenticatedPilotagesRequestTypeDelaysIndexRouteImport } from './routes/_authenticated/pilotages/request-type-delays/index'
import { Route as AuthenticatedPilotagesProvidersIndexRouteImport } from './routes/_authenticated/pilotages/providers/index'
import { Route as AuthenticatedPilotagesProviderServiceCategoriesIndexRouteImport } from './routes/_authenticated/pilotages/provider-service-categories/index'
import { Route as AuthenticatedPilotagesProviderDisponibilitiesIndexRouteImport } from './routes/_authenticated/pilotages/provider-disponibilities/index'
import { Route as AuthenticatedPilotagesHolidaysIndexRouteImport } from './routes/_authenticated/pilotages/holidays/index'
import { Route as AuthenticatedPilotagesFlowsIndexRouteImport } from './routes/_authenticated/pilotages/flows/index'
import { Route as AuthenticatedPilotagesDeliverablesIndexRouteImport } from './routes/_authenticated/pilotages/deliverables/index'
import { Route as AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRouteImport } from './routes/_authenticated/pilotages/deliverable-delay-request-types/index'
import { Route as AuthenticatedPilotagesDeliverableDelayFlowsIndexRouteImport } from './routes/_authenticated/pilotages/deliverable-delay-flows/index'
import { Route as AuthenticatedPilotagesDelayTypesIndexRouteImport } from './routes/_authenticated/pilotages/delay-types/index'
import { Route as AuthenticatedPilotagesConformityTypesIndexRouteImport } from './routes/_authenticated/pilotages/conformity-types/index'
import { Route as AuthenticatedPilotagesClientsIndexRouteImport } from './routes/_authenticated/pilotages/clients/index'
import { Route as AuthenticatedAdministrationsRolesIndexRouteImport } from './routes/_authenticated/administrations/roles/index'
import { Route as AuthenticatedPilotagesUsersCreateRouteImport } from './routes/_authenticated/pilotages/users/create'
import { Route as AuthenticatedPilotagesTeamsCreateRouteImport } from './routes/_authenticated/pilotages/teams/create'
import { Route as AuthenticatedPilotagesSubdivisionClientsCreateRouteImport } from './routes/_authenticated/pilotages/subdivision-clients/create'
import { Route as AuthenticatedPilotagesServicesCreateRouteImport } from './routes/_authenticated/pilotages/services/create'
import { Route as AuthenticatedPilotagesServiceCategoriesCreateRouteImport } from './routes/_authenticated/pilotages/service-categories/create'
import { Route as AuthenticatedPilotagesSectorsCreateRouteImport } from './routes/_authenticated/pilotages/sectors/create'
import { Route as AuthenticatedPilotagesRequisitionTypesCreateRouteImport } from './routes/_authenticated/pilotages/requisition-types/create'
import { Route as AuthenticatedPilotagesRequestTypesCreateRouteImport } from './routes/_authenticated/pilotages/request-types/create'
import { Route as AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRouteImport } from './routes/_authenticated/pilotages/request-type-service-categories/create'
import { Route as AuthenticatedPilotagesRequestTypeDelaysCreateRouteImport } from './routes/_authenticated/pilotages/request-type-delays/create'
import { Route as AuthenticatedPilotagesProvidersCreateRouteImport } from './routes/_authenticated/pilotages/providers/create'
import { Route as AuthenticatedPilotagesProviderServiceCategoriesCreateRouteImport } from './routes/_authenticated/pilotages/provider-service-categories/create'
import { Route as AuthenticatedPilotagesProviderDisponibilitiesCreateRouteImport } from './routes/_authenticated/pilotages/provider-disponibilities/create'
import { Route as AuthenticatedPilotagesHolidaysCreateRouteImport } from './routes/_authenticated/pilotages/holidays/create'
import { Route as AuthenticatedPilotagesFlowsCreateRouteImport } from './routes/_authenticated/pilotages/flows/create'
import { Route as AuthenticatedPilotagesDeliverablesCreateRouteImport } from './routes/_authenticated/pilotages/deliverables/create'
import { Route as AuthenticatedPilotagesDelayTypesCreateRouteImport } from './routes/_authenticated/pilotages/delay-types/create'
import { Route as AuthenticatedPilotagesConformityTypesCreateRouteImport } from './routes/_authenticated/pilotages/conformity-types/create'
import { Route as AuthenticatedPilotagesClientsCreateRouteImport } from './routes/_authenticated/pilotages/clients/create'
import { Route as AuthenticatedAdministrationsRolesCreateRouteImport } from './routes/_authenticated/administrations/roles/create'
import { Route as AuthenticatedPilotagesTeamsUpdateIdRouteImport } from './routes/_authenticated/pilotages/teams/update/$id'
import { Route as AuthenticatedPilotagesSubdivisionClientsUpdateIdRouteImport } from './routes/_authenticated/pilotages/subdivision-clients/update/$id'
import { Route as AuthenticatedPilotagesServicesUpdateIdRouteImport } from './routes/_authenticated/pilotages/services/update/$id'
import { Route as AuthenticatedPilotagesServiceCategoriesUpdateIdRouteImport } from './routes/_authenticated/pilotages/service-categories/update/$id'
import { Route as AuthenticatedPilotagesSectorsUpdateIdRouteImport } from './routes/_authenticated/pilotages/sectors/update/$id'
import { Route as AuthenticatedPilotagesRequisitionTypesUpdateIdRouteImport } from './routes/_authenticated/pilotages/requisition-types/update/$id'
import { Route as AuthenticatedPilotagesRequestTypesUpdateIdRouteImport } from './routes/_authenticated/pilotages/request-types/update/$id'
import { Route as AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRouteImport } from './routes/_authenticated/pilotages/request-type-service-categories/update/$id'
import { Route as AuthenticatedPilotagesRequestTypeDelaysUpdateIdRouteImport } from './routes/_authenticated/pilotages/request-type-delays/update/$id'
import { Route as AuthenticatedPilotagesProvidersUpdateIdRouteImport } from './routes/_authenticated/pilotages/providers/update/$id'
import { Route as AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRouteImport } from './routes/_authenticated/pilotages/provider-service-categories/update/$id'
import { Route as AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRouteImport } from './routes/_authenticated/pilotages/provider-disponibilities/update/$id'
import { Route as AuthenticatedPilotagesHolidaysUpdateIdRouteImport } from './routes/_authenticated/pilotages/holidays/update/$id'
import { Route as AuthenticatedPilotagesFlowsUpdateIdRouteImport } from './routes/_authenticated/pilotages/flows/update/$id'
import { Route as AuthenticatedPilotagesDeliverablesUpdateIdRouteImport } from './routes/_authenticated/pilotages/deliverables/update/$id'
import { Route as AuthenticatedPilotagesDelayTypesUpdateIdRouteImport } from './routes/_authenticated/pilotages/delay-types/update/$id'
import { Route as AuthenticatedPilotagesConformityTypesUpdateIdRouteImport } from './routes/_authenticated/pilotages/conformity-types/update/$id'
import { Route as AuthenticatedPilotagesClientsUpdateIdRouteImport } from './routes/_authenticated/pilotages/clients/update/$id'
import { Route as AuthenticatedAdministrationsRolesUpdateIdRouteImport } from './routes/_authenticated/administrations/roles/update/$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const GuestVerifyEmailTokenRoute = GuestVerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => GuestRoute,
} as any)
const GuestloginLoginRoute = GuestloginLoginRouteImport.update({
  id: '/(login)/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedPilotagesUsersIndexRoute =
  AuthenticatedPilotagesUsersIndexRouteImport.update({
    id: '/pilotages/users/',
    path: '/pilotages/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesTestTableIndexRoute =
  AuthenticatedPilotagesTestTableIndexRouteImport.update({
    id: '/pilotages/test-table/',
    path: '/pilotages/test-table/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesTeamsIndexRoute =
  AuthenticatedPilotagesTeamsIndexRouteImport.update({
    id: '/pilotages/teams/',
    path: '/pilotages/teams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesSubdivisionClientsIndexRoute =
  AuthenticatedPilotagesSubdivisionClientsIndexRouteImport.update({
    id: '/pilotages/subdivision-clients/',
    path: '/pilotages/subdivision-clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesServicesIndexRoute =
  AuthenticatedPilotagesServicesIndexRouteImport.update({
    id: '/pilotages/services/',
    path: '/pilotages/services/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesServiceCategoriesIndexRoute =
  AuthenticatedPilotagesServiceCategoriesIndexRouteImport.update({
    id: '/pilotages/service-categories/',
    path: '/pilotages/service-categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesSectorsIndexRoute =
  AuthenticatedPilotagesSectorsIndexRouteImport.update({
    id: '/pilotages/sectors/',
    path: '/pilotages/sectors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequisitionTypesIndexRoute =
  AuthenticatedPilotagesRequisitionTypesIndexRouteImport.update({
    id: '/pilotages/requisition-types/',
    path: '/pilotages/requisition-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypesIndexRoute =
  AuthenticatedPilotagesRequestTypesIndexRouteImport.update({
    id: '/pilotages/request-types/',
    path: '/pilotages/request-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute =
  AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRouteImport.update({
    id: '/pilotages/request-type-service-categories/',
    path: '/pilotages/request-type-service-categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypeDelaysIndexRoute =
  AuthenticatedPilotagesRequestTypeDelaysIndexRouteImport.update({
    id: '/pilotages/request-type-delays/',
    path: '/pilotages/request-type-delays/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProvidersIndexRoute =
  AuthenticatedPilotagesProvidersIndexRouteImport.update({
    id: '/pilotages/providers/',
    path: '/pilotages/providers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProviderServiceCategoriesIndexRoute =
  AuthenticatedPilotagesProviderServiceCategoriesIndexRouteImport.update({
    id: '/pilotages/provider-service-categories/',
    path: '/pilotages/provider-service-categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProviderDisponibilitiesIndexRoute =
  AuthenticatedPilotagesProviderDisponibilitiesIndexRouteImport.update({
    id: '/pilotages/provider-disponibilities/',
    path: '/pilotages/provider-disponibilities/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesHolidaysIndexRoute =
  AuthenticatedPilotagesHolidaysIndexRouteImport.update({
    id: '/pilotages/holidays/',
    path: '/pilotages/holidays/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesFlowsIndexRoute =
  AuthenticatedPilotagesFlowsIndexRouteImport.update({
    id: '/pilotages/flows/',
    path: '/pilotages/flows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDeliverablesIndexRoute =
  AuthenticatedPilotagesDeliverablesIndexRouteImport.update({
    id: '/pilotages/deliverables/',
    path: '/pilotages/deliverables/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute =
  AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRouteImport.update({
    id: '/pilotages/deliverable-delay-request-types/',
    path: '/pilotages/deliverable-delay-request-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute =
  AuthenticatedPilotagesDeliverableDelayFlowsIndexRouteImport.update({
    id: '/pilotages/deliverable-delay-flows/',
    path: '/pilotages/deliverable-delay-flows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDelayTypesIndexRoute =
  AuthenticatedPilotagesDelayTypesIndexRouteImport.update({
    id: '/pilotages/delay-types/',
    path: '/pilotages/delay-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesConformityTypesIndexRoute =
  AuthenticatedPilotagesConformityTypesIndexRouteImport.update({
    id: '/pilotages/conformity-types/',
    path: '/pilotages/conformity-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesClientsIndexRoute =
  AuthenticatedPilotagesClientsIndexRouteImport.update({
    id: '/pilotages/clients/',
    path: '/pilotages/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministrationsRolesIndexRoute =
  AuthenticatedAdministrationsRolesIndexRouteImport.update({
    id: '/administrations/roles/',
    path: '/administrations/roles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesUsersCreateRoute =
  AuthenticatedPilotagesUsersCreateRouteImport.update({
    id: '/pilotages/users/create',
    path: '/pilotages/users/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesTeamsCreateRoute =
  AuthenticatedPilotagesTeamsCreateRouteImport.update({
    id: '/pilotages/teams/create',
    path: '/pilotages/teams/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesSubdivisionClientsCreateRoute =
  AuthenticatedPilotagesSubdivisionClientsCreateRouteImport.update({
    id: '/pilotages/subdivision-clients/create',
    path: '/pilotages/subdivision-clients/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesServicesCreateRoute =
  AuthenticatedPilotagesServicesCreateRouteImport.update({
    id: '/pilotages/services/create',
    path: '/pilotages/services/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesServiceCategoriesCreateRoute =
  AuthenticatedPilotagesServiceCategoriesCreateRouteImport.update({
    id: '/pilotages/service-categories/create',
    path: '/pilotages/service-categories/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesSectorsCreateRoute =
  AuthenticatedPilotagesSectorsCreateRouteImport.update({
    id: '/pilotages/sectors/create',
    path: '/pilotages/sectors/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequisitionTypesCreateRoute =
  AuthenticatedPilotagesRequisitionTypesCreateRouteImport.update({
    id: '/pilotages/requisition-types/create',
    path: '/pilotages/requisition-types/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypesCreateRoute =
  AuthenticatedPilotagesRequestTypesCreateRouteImport.update({
    id: '/pilotages/request-types/create',
    path: '/pilotages/request-types/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute =
  AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRouteImport.update({
    id: '/pilotages/request-type-service-categories/create',
    path: '/pilotages/request-type-service-categories/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypeDelaysCreateRoute =
  AuthenticatedPilotagesRequestTypeDelaysCreateRouteImport.update({
    id: '/pilotages/request-type-delays/create',
    path: '/pilotages/request-type-delays/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProvidersCreateRoute =
  AuthenticatedPilotagesProvidersCreateRouteImport.update({
    id: '/pilotages/providers/create',
    path: '/pilotages/providers/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProviderServiceCategoriesCreateRoute =
  AuthenticatedPilotagesProviderServiceCategoriesCreateRouteImport.update({
    id: '/pilotages/provider-service-categories/create',
    path: '/pilotages/provider-service-categories/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProviderDisponibilitiesCreateRoute =
  AuthenticatedPilotagesProviderDisponibilitiesCreateRouteImport.update({
    id: '/pilotages/provider-disponibilities/create',
    path: '/pilotages/provider-disponibilities/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesHolidaysCreateRoute =
  AuthenticatedPilotagesHolidaysCreateRouteImport.update({
    id: '/pilotages/holidays/create',
    path: '/pilotages/holidays/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesFlowsCreateRoute =
  AuthenticatedPilotagesFlowsCreateRouteImport.update({
    id: '/pilotages/flows/create',
    path: '/pilotages/flows/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDeliverablesCreateRoute =
  AuthenticatedPilotagesDeliverablesCreateRouteImport.update({
    id: '/pilotages/deliverables/create',
    path: '/pilotages/deliverables/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDelayTypesCreateRoute =
  AuthenticatedPilotagesDelayTypesCreateRouteImport.update({
    id: '/pilotages/delay-types/create',
    path: '/pilotages/delay-types/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesConformityTypesCreateRoute =
  AuthenticatedPilotagesConformityTypesCreateRouteImport.update({
    id: '/pilotages/conformity-types/create',
    path: '/pilotages/conformity-types/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesClientsCreateRoute =
  AuthenticatedPilotagesClientsCreateRouteImport.update({
    id: '/pilotages/clients/create',
    path: '/pilotages/clients/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministrationsRolesCreateRoute =
  AuthenticatedAdministrationsRolesCreateRouteImport.update({
    id: '/administrations/roles/create',
    path: '/administrations/roles/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesTeamsUpdateIdRoute =
  AuthenticatedPilotagesTeamsUpdateIdRouteImport.update({
    id: '/pilotages/teams/update/$id',
    path: '/pilotages/teams/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute =
  AuthenticatedPilotagesSubdivisionClientsUpdateIdRouteImport.update({
    id: '/pilotages/subdivision-clients/update/$id',
    path: '/pilotages/subdivision-clients/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesServicesUpdateIdRoute =
  AuthenticatedPilotagesServicesUpdateIdRouteImport.update({
    id: '/pilotages/services/update/$id',
    path: '/pilotages/services/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesServiceCategoriesUpdateIdRoute =
  AuthenticatedPilotagesServiceCategoriesUpdateIdRouteImport.update({
    id: '/pilotages/service-categories/update/$id',
    path: '/pilotages/service-categories/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesSectorsUpdateIdRoute =
  AuthenticatedPilotagesSectorsUpdateIdRouteImport.update({
    id: '/pilotages/sectors/update/$id',
    path: '/pilotages/sectors/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequisitionTypesUpdateIdRoute =
  AuthenticatedPilotagesRequisitionTypesUpdateIdRouteImport.update({
    id: '/pilotages/requisition-types/update/$id',
    path: '/pilotages/requisition-types/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypesUpdateIdRoute =
  AuthenticatedPilotagesRequestTypesUpdateIdRouteImport.update({
    id: '/pilotages/request-types/update/$id',
    path: '/pilotages/request-types/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute =
  AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRouteImport.update({
    id: '/pilotages/request-type-service-categories/update/$id',
    path: '/pilotages/request-type-service-categories/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute =
  AuthenticatedPilotagesRequestTypeDelaysUpdateIdRouteImport.update({
    id: '/pilotages/request-type-delays/update/$id',
    path: '/pilotages/request-type-delays/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProvidersUpdateIdRoute =
  AuthenticatedPilotagesProvidersUpdateIdRouteImport.update({
    id: '/pilotages/providers/update/$id',
    path: '/pilotages/providers/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute =
  AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRouteImport.update({
    id: '/pilotages/provider-service-categories/update/$id',
    path: '/pilotages/provider-service-categories/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute =
  AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRouteImport.update({
    id: '/pilotages/provider-disponibilities/update/$id',
    path: '/pilotages/provider-disponibilities/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesHolidaysUpdateIdRoute =
  AuthenticatedPilotagesHolidaysUpdateIdRouteImport.update({
    id: '/pilotages/holidays/update/$id',
    path: '/pilotages/holidays/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesFlowsUpdateIdRoute =
  AuthenticatedPilotagesFlowsUpdateIdRouteImport.update({
    id: '/pilotages/flows/update/$id',
    path: '/pilotages/flows/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDeliverablesUpdateIdRoute =
  AuthenticatedPilotagesDeliverablesUpdateIdRouteImport.update({
    id: '/pilotages/deliverables/update/$id',
    path: '/pilotages/deliverables/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesDelayTypesUpdateIdRoute =
  AuthenticatedPilotagesDelayTypesUpdateIdRouteImport.update({
    id: '/pilotages/delay-types/update/$id',
    path: '/pilotages/delay-types/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesConformityTypesUpdateIdRoute =
  AuthenticatedPilotagesConformityTypesUpdateIdRouteImport.update({
    id: '/pilotages/conformity-types/update/$id',
    path: '/pilotages/conformity-types/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPilotagesClientsUpdateIdRoute =
  AuthenticatedPilotagesClientsUpdateIdRouteImport.update({
    id: '/pilotages/clients/update/$id',
    path: '/pilotages/clients/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministrationsRolesUpdateIdRoute =
  AuthenticatedAdministrationsRolesUpdateIdRouteImport.update({
    id: '/administrations/roles/update/$id',
    path: '/administrations/roles/update/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '': typeof GuestRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof GuestloginLoginRoute
  '/verify-email/$token': typeof GuestVerifyEmailTokenRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/administrations/roles/create': typeof AuthenticatedAdministrationsRolesCreateRoute
  '/pilotages/clients/create': typeof AuthenticatedPilotagesClientsCreateRoute
  '/pilotages/conformity-types/create': typeof AuthenticatedPilotagesConformityTypesCreateRoute
  '/pilotages/delay-types/create': typeof AuthenticatedPilotagesDelayTypesCreateRoute
  '/pilotages/deliverables/create': typeof AuthenticatedPilotagesDeliverablesCreateRoute
  '/pilotages/flows/create': typeof AuthenticatedPilotagesFlowsCreateRoute
  '/pilotages/holidays/create': typeof AuthenticatedPilotagesHolidaysCreateRoute
  '/pilotages/provider-disponibilities/create': typeof AuthenticatedPilotagesProviderDisponibilitiesCreateRoute
  '/pilotages/provider-service-categories/create': typeof AuthenticatedPilotagesProviderServiceCategoriesCreateRoute
  '/pilotages/providers/create': typeof AuthenticatedPilotagesProvidersCreateRoute
  '/pilotages/request-type-delays/create': typeof AuthenticatedPilotagesRequestTypeDelaysCreateRoute
  '/pilotages/request-type-service-categories/create': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute
  '/pilotages/request-types/create': typeof AuthenticatedPilotagesRequestTypesCreateRoute
  '/pilotages/requisition-types/create': typeof AuthenticatedPilotagesRequisitionTypesCreateRoute
  '/pilotages/sectors/create': typeof AuthenticatedPilotagesSectorsCreateRoute
  '/pilotages/service-categories/create': typeof AuthenticatedPilotagesServiceCategoriesCreateRoute
  '/pilotages/services/create': typeof AuthenticatedPilotagesServicesCreateRoute
  '/pilotages/subdivision-clients/create': typeof AuthenticatedPilotagesSubdivisionClientsCreateRoute
  '/pilotages/teams/create': typeof AuthenticatedPilotagesTeamsCreateRoute
  '/pilotages/users/create': typeof AuthenticatedPilotagesUsersCreateRoute
  '/administrations/roles': typeof AuthenticatedAdministrationsRolesIndexRoute
  '/pilotages/clients': typeof AuthenticatedPilotagesClientsIndexRoute
  '/pilotages/conformity-types': typeof AuthenticatedPilotagesConformityTypesIndexRoute
  '/pilotages/delay-types': typeof AuthenticatedPilotagesDelayTypesIndexRoute
  '/pilotages/deliverable-delay-flows': typeof AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute
  '/pilotages/deliverable-delay-request-types': typeof AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute
  '/pilotages/deliverables': typeof AuthenticatedPilotagesDeliverablesIndexRoute
  '/pilotages/flows': typeof AuthenticatedPilotagesFlowsIndexRoute
  '/pilotages/holidays': typeof AuthenticatedPilotagesHolidaysIndexRoute
  '/pilotages/provider-disponibilities': typeof AuthenticatedPilotagesProviderDisponibilitiesIndexRoute
  '/pilotages/provider-service-categories': typeof AuthenticatedPilotagesProviderServiceCategoriesIndexRoute
  '/pilotages/providers': typeof AuthenticatedPilotagesProvidersIndexRoute
  '/pilotages/request-type-delays': typeof AuthenticatedPilotagesRequestTypeDelaysIndexRoute
  '/pilotages/request-type-service-categories': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute
  '/pilotages/request-types': typeof AuthenticatedPilotagesRequestTypesIndexRoute
  '/pilotages/requisition-types': typeof AuthenticatedPilotagesRequisitionTypesIndexRoute
  '/pilotages/sectors': typeof AuthenticatedPilotagesSectorsIndexRoute
  '/pilotages/service-categories': typeof AuthenticatedPilotagesServiceCategoriesIndexRoute
  '/pilotages/services': typeof AuthenticatedPilotagesServicesIndexRoute
  '/pilotages/subdivision-clients': typeof AuthenticatedPilotagesSubdivisionClientsIndexRoute
  '/pilotages/teams': typeof AuthenticatedPilotagesTeamsIndexRoute
  '/pilotages/test-table': typeof AuthenticatedPilotagesTestTableIndexRoute
  '/pilotages/users': typeof AuthenticatedPilotagesUsersIndexRoute
  '/administrations/roles/update/$id': typeof AuthenticatedAdministrationsRolesUpdateIdRoute
  '/pilotages/clients/update/$id': typeof AuthenticatedPilotagesClientsUpdateIdRoute
  '/pilotages/conformity-types/update/$id': typeof AuthenticatedPilotagesConformityTypesUpdateIdRoute
  '/pilotages/delay-types/update/$id': typeof AuthenticatedPilotagesDelayTypesUpdateIdRoute
  '/pilotages/deliverables/update/$id': typeof AuthenticatedPilotagesDeliverablesUpdateIdRoute
  '/pilotages/flows/update/$id': typeof AuthenticatedPilotagesFlowsUpdateIdRoute
  '/pilotages/holidays/update/$id': typeof AuthenticatedPilotagesHolidaysUpdateIdRoute
  '/pilotages/provider-disponibilities/update/$id': typeof AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute
  '/pilotages/provider-service-categories/update/$id': typeof AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute
  '/pilotages/providers/update/$id': typeof AuthenticatedPilotagesProvidersUpdateIdRoute
  '/pilotages/request-type-delays/update/$id': typeof AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute
  '/pilotages/request-type-service-categories/update/$id': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute
  '/pilotages/request-types/update/$id': typeof AuthenticatedPilotagesRequestTypesUpdateIdRoute
  '/pilotages/requisition-types/update/$id': typeof AuthenticatedPilotagesRequisitionTypesUpdateIdRoute
  '/pilotages/sectors/update/$id': typeof AuthenticatedPilotagesSectorsUpdateIdRoute
  '/pilotages/service-categories/update/$id': typeof AuthenticatedPilotagesServiceCategoriesUpdateIdRoute
  '/pilotages/services/update/$id': typeof AuthenticatedPilotagesServicesUpdateIdRoute
  '/pilotages/subdivision-clients/update/$id': typeof AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute
  '/pilotages/teams/update/$id': typeof AuthenticatedPilotagesTeamsUpdateIdRoute
}
export interface FileRoutesByTo {
  '': typeof GuestRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof GuestloginLoginRoute
  '/verify-email/$token': typeof GuestVerifyEmailTokenRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/administrations/roles/create': typeof AuthenticatedAdministrationsRolesCreateRoute
  '/pilotages/clients/create': typeof AuthenticatedPilotagesClientsCreateRoute
  '/pilotages/conformity-types/create': typeof AuthenticatedPilotagesConformityTypesCreateRoute
  '/pilotages/delay-types/create': typeof AuthenticatedPilotagesDelayTypesCreateRoute
  '/pilotages/deliverables/create': typeof AuthenticatedPilotagesDeliverablesCreateRoute
  '/pilotages/flows/create': typeof AuthenticatedPilotagesFlowsCreateRoute
  '/pilotages/holidays/create': typeof AuthenticatedPilotagesHolidaysCreateRoute
  '/pilotages/provider-disponibilities/create': typeof AuthenticatedPilotagesProviderDisponibilitiesCreateRoute
  '/pilotages/provider-service-categories/create': typeof AuthenticatedPilotagesProviderServiceCategoriesCreateRoute
  '/pilotages/providers/create': typeof AuthenticatedPilotagesProvidersCreateRoute
  '/pilotages/request-type-delays/create': typeof AuthenticatedPilotagesRequestTypeDelaysCreateRoute
  '/pilotages/request-type-service-categories/create': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute
  '/pilotages/request-types/create': typeof AuthenticatedPilotagesRequestTypesCreateRoute
  '/pilotages/requisition-types/create': typeof AuthenticatedPilotagesRequisitionTypesCreateRoute
  '/pilotages/sectors/create': typeof AuthenticatedPilotagesSectorsCreateRoute
  '/pilotages/service-categories/create': typeof AuthenticatedPilotagesServiceCategoriesCreateRoute
  '/pilotages/services/create': typeof AuthenticatedPilotagesServicesCreateRoute
  '/pilotages/subdivision-clients/create': typeof AuthenticatedPilotagesSubdivisionClientsCreateRoute
  '/pilotages/teams/create': typeof AuthenticatedPilotagesTeamsCreateRoute
  '/pilotages/users/create': typeof AuthenticatedPilotagesUsersCreateRoute
  '/administrations/roles': typeof AuthenticatedAdministrationsRolesIndexRoute
  '/pilotages/clients': typeof AuthenticatedPilotagesClientsIndexRoute
  '/pilotages/conformity-types': typeof AuthenticatedPilotagesConformityTypesIndexRoute
  '/pilotages/delay-types': typeof AuthenticatedPilotagesDelayTypesIndexRoute
  '/pilotages/deliverable-delay-flows': typeof AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute
  '/pilotages/deliverable-delay-request-types': typeof AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute
  '/pilotages/deliverables': typeof AuthenticatedPilotagesDeliverablesIndexRoute
  '/pilotages/flows': typeof AuthenticatedPilotagesFlowsIndexRoute
  '/pilotages/holidays': typeof AuthenticatedPilotagesHolidaysIndexRoute
  '/pilotages/provider-disponibilities': typeof AuthenticatedPilotagesProviderDisponibilitiesIndexRoute
  '/pilotages/provider-service-categories': typeof AuthenticatedPilotagesProviderServiceCategoriesIndexRoute
  '/pilotages/providers': typeof AuthenticatedPilotagesProvidersIndexRoute
  '/pilotages/request-type-delays': typeof AuthenticatedPilotagesRequestTypeDelaysIndexRoute
  '/pilotages/request-type-service-categories': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute
  '/pilotages/request-types': typeof AuthenticatedPilotagesRequestTypesIndexRoute
  '/pilotages/requisition-types': typeof AuthenticatedPilotagesRequisitionTypesIndexRoute
  '/pilotages/sectors': typeof AuthenticatedPilotagesSectorsIndexRoute
  '/pilotages/service-categories': typeof AuthenticatedPilotagesServiceCategoriesIndexRoute
  '/pilotages/services': typeof AuthenticatedPilotagesServicesIndexRoute
  '/pilotages/subdivision-clients': typeof AuthenticatedPilotagesSubdivisionClientsIndexRoute
  '/pilotages/teams': typeof AuthenticatedPilotagesTeamsIndexRoute
  '/pilotages/test-table': typeof AuthenticatedPilotagesTestTableIndexRoute
  '/pilotages/users': typeof AuthenticatedPilotagesUsersIndexRoute
  '/administrations/roles/update/$id': typeof AuthenticatedAdministrationsRolesUpdateIdRoute
  '/pilotages/clients/update/$id': typeof AuthenticatedPilotagesClientsUpdateIdRoute
  '/pilotages/conformity-types/update/$id': typeof AuthenticatedPilotagesConformityTypesUpdateIdRoute
  '/pilotages/delay-types/update/$id': typeof AuthenticatedPilotagesDelayTypesUpdateIdRoute
  '/pilotages/deliverables/update/$id': typeof AuthenticatedPilotagesDeliverablesUpdateIdRoute
  '/pilotages/flows/update/$id': typeof AuthenticatedPilotagesFlowsUpdateIdRoute
  '/pilotages/holidays/update/$id': typeof AuthenticatedPilotagesHolidaysUpdateIdRoute
  '/pilotages/provider-disponibilities/update/$id': typeof AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute
  '/pilotages/provider-service-categories/update/$id': typeof AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute
  '/pilotages/providers/update/$id': typeof AuthenticatedPilotagesProvidersUpdateIdRoute
  '/pilotages/request-type-delays/update/$id': typeof AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute
  '/pilotages/request-type-service-categories/update/$id': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute
  '/pilotages/request-types/update/$id': typeof AuthenticatedPilotagesRequestTypesUpdateIdRoute
  '/pilotages/requisition-types/update/$id': typeof AuthenticatedPilotagesRequisitionTypesUpdateIdRoute
  '/pilotages/sectors/update/$id': typeof AuthenticatedPilotagesSectorsUpdateIdRoute
  '/pilotages/service-categories/update/$id': typeof AuthenticatedPilotagesServiceCategoriesUpdateIdRoute
  '/pilotages/services/update/$id': typeof AuthenticatedPilotagesServicesUpdateIdRoute
  '/pilotages/subdivision-clients/update/$id': typeof AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute
  '/pilotages/teams/update/$id': typeof AuthenticatedPilotagesTeamsUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_guest/(login)/login': typeof GuestloginLoginRoute
  '/_guest/verify-email/$token': typeof GuestVerifyEmailTokenRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/administrations/roles/create': typeof AuthenticatedAdministrationsRolesCreateRoute
  '/_authenticated/pilotages/clients/create': typeof AuthenticatedPilotagesClientsCreateRoute
  '/_authenticated/pilotages/conformity-types/create': typeof AuthenticatedPilotagesConformityTypesCreateRoute
  '/_authenticated/pilotages/delay-types/create': typeof AuthenticatedPilotagesDelayTypesCreateRoute
  '/_authenticated/pilotages/deliverables/create': typeof AuthenticatedPilotagesDeliverablesCreateRoute
  '/_authenticated/pilotages/flows/create': typeof AuthenticatedPilotagesFlowsCreateRoute
  '/_authenticated/pilotages/holidays/create': typeof AuthenticatedPilotagesHolidaysCreateRoute
  '/_authenticated/pilotages/provider-disponibilities/create': typeof AuthenticatedPilotagesProviderDisponibilitiesCreateRoute
  '/_authenticated/pilotages/provider-service-categories/create': typeof AuthenticatedPilotagesProviderServiceCategoriesCreateRoute
  '/_authenticated/pilotages/providers/create': typeof AuthenticatedPilotagesProvidersCreateRoute
  '/_authenticated/pilotages/request-type-delays/create': typeof AuthenticatedPilotagesRequestTypeDelaysCreateRoute
  '/_authenticated/pilotages/request-type-service-categories/create': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute
  '/_authenticated/pilotages/request-types/create': typeof AuthenticatedPilotagesRequestTypesCreateRoute
  '/_authenticated/pilotages/requisition-types/create': typeof AuthenticatedPilotagesRequisitionTypesCreateRoute
  '/_authenticated/pilotages/sectors/create': typeof AuthenticatedPilotagesSectorsCreateRoute
  '/_authenticated/pilotages/service-categories/create': typeof AuthenticatedPilotagesServiceCategoriesCreateRoute
  '/_authenticated/pilotages/services/create': typeof AuthenticatedPilotagesServicesCreateRoute
  '/_authenticated/pilotages/subdivision-clients/create': typeof AuthenticatedPilotagesSubdivisionClientsCreateRoute
  '/_authenticated/pilotages/teams/create': typeof AuthenticatedPilotagesTeamsCreateRoute
  '/_authenticated/pilotages/users/create': typeof AuthenticatedPilotagesUsersCreateRoute
  '/_authenticated/administrations/roles/': typeof AuthenticatedAdministrationsRolesIndexRoute
  '/_authenticated/pilotages/clients/': typeof AuthenticatedPilotagesClientsIndexRoute
  '/_authenticated/pilotages/conformity-types/': typeof AuthenticatedPilotagesConformityTypesIndexRoute
  '/_authenticated/pilotages/delay-types/': typeof AuthenticatedPilotagesDelayTypesIndexRoute
  '/_authenticated/pilotages/deliverable-delay-flows/': typeof AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute
  '/_authenticated/pilotages/deliverable-delay-request-types/': typeof AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute
  '/_authenticated/pilotages/deliverables/': typeof AuthenticatedPilotagesDeliverablesIndexRoute
  '/_authenticated/pilotages/flows/': typeof AuthenticatedPilotagesFlowsIndexRoute
  '/_authenticated/pilotages/holidays/': typeof AuthenticatedPilotagesHolidaysIndexRoute
  '/_authenticated/pilotages/provider-disponibilities/': typeof AuthenticatedPilotagesProviderDisponibilitiesIndexRoute
  '/_authenticated/pilotages/provider-service-categories/': typeof AuthenticatedPilotagesProviderServiceCategoriesIndexRoute
  '/_authenticated/pilotages/providers/': typeof AuthenticatedPilotagesProvidersIndexRoute
  '/_authenticated/pilotages/request-type-delays/': typeof AuthenticatedPilotagesRequestTypeDelaysIndexRoute
  '/_authenticated/pilotages/request-type-service-categories/': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute
  '/_authenticated/pilotages/request-types/': typeof AuthenticatedPilotagesRequestTypesIndexRoute
  '/_authenticated/pilotages/requisition-types/': typeof AuthenticatedPilotagesRequisitionTypesIndexRoute
  '/_authenticated/pilotages/sectors/': typeof AuthenticatedPilotagesSectorsIndexRoute
  '/_authenticated/pilotages/service-categories/': typeof AuthenticatedPilotagesServiceCategoriesIndexRoute
  '/_authenticated/pilotages/services/': typeof AuthenticatedPilotagesServicesIndexRoute
  '/_authenticated/pilotages/subdivision-clients/': typeof AuthenticatedPilotagesSubdivisionClientsIndexRoute
  '/_authenticated/pilotages/teams/': typeof AuthenticatedPilotagesTeamsIndexRoute
  '/_authenticated/pilotages/test-table/': typeof AuthenticatedPilotagesTestTableIndexRoute
  '/_authenticated/pilotages/users/': typeof AuthenticatedPilotagesUsersIndexRoute
  '/_authenticated/administrations/roles/update/$id': typeof AuthenticatedAdministrationsRolesUpdateIdRoute
  '/_authenticated/pilotages/clients/update/$id': typeof AuthenticatedPilotagesClientsUpdateIdRoute
  '/_authenticated/pilotages/conformity-types/update/$id': typeof AuthenticatedPilotagesConformityTypesUpdateIdRoute
  '/_authenticated/pilotages/delay-types/update/$id': typeof AuthenticatedPilotagesDelayTypesUpdateIdRoute
  '/_authenticated/pilotages/deliverables/update/$id': typeof AuthenticatedPilotagesDeliverablesUpdateIdRoute
  '/_authenticated/pilotages/flows/update/$id': typeof AuthenticatedPilotagesFlowsUpdateIdRoute
  '/_authenticated/pilotages/holidays/update/$id': typeof AuthenticatedPilotagesHolidaysUpdateIdRoute
  '/_authenticated/pilotages/provider-disponibilities/update/$id': typeof AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute
  '/_authenticated/pilotages/provider-service-categories/update/$id': typeof AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute
  '/_authenticated/pilotages/providers/update/$id': typeof AuthenticatedPilotagesProvidersUpdateIdRoute
  '/_authenticated/pilotages/request-type-delays/update/$id': typeof AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute
  '/_authenticated/pilotages/request-type-service-categories/update/$id': typeof AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute
  '/_authenticated/pilotages/request-types/update/$id': typeof AuthenticatedPilotagesRequestTypesUpdateIdRoute
  '/_authenticated/pilotages/requisition-types/update/$id': typeof AuthenticatedPilotagesRequisitionTypesUpdateIdRoute
  '/_authenticated/pilotages/sectors/update/$id': typeof AuthenticatedPilotagesSectorsUpdateIdRoute
  '/_authenticated/pilotages/service-categories/update/$id': typeof AuthenticatedPilotagesServiceCategoriesUpdateIdRoute
  '/_authenticated/pilotages/services/update/$id': typeof AuthenticatedPilotagesServicesUpdateIdRoute
  '/_authenticated/pilotages/subdivision-clients/update/$id': typeof AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute
  '/_authenticated/pilotages/teams/update/$id': typeof AuthenticatedPilotagesTeamsUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/unauthorized'
    | '/'
    | '/login'
    | '/verify-email/$token'
    | '/profile'
    | '/administrations/roles/create'
    | '/pilotages/clients/create'
    | '/pilotages/conformity-types/create'
    | '/pilotages/delay-types/create'
    | '/pilotages/deliverables/create'
    | '/pilotages/flows/create'
    | '/pilotages/holidays/create'
    | '/pilotages/provider-disponibilities/create'
    | '/pilotages/provider-service-categories/create'
    | '/pilotages/providers/create'
    | '/pilotages/request-type-delays/create'
    | '/pilotages/request-type-service-categories/create'
    | '/pilotages/request-types/create'
    | '/pilotages/requisition-types/create'
    | '/pilotages/sectors/create'
    | '/pilotages/service-categories/create'
    | '/pilotages/services/create'
    | '/pilotages/subdivision-clients/create'
    | '/pilotages/teams/create'
    | '/pilotages/users/create'
    | '/administrations/roles'
    | '/pilotages/clients'
    | '/pilotages/conformity-types'
    | '/pilotages/delay-types'
    | '/pilotages/deliverable-delay-flows'
    | '/pilotages/deliverable-delay-request-types'
    | '/pilotages/deliverables'
    | '/pilotages/flows'
    | '/pilotages/holidays'
    | '/pilotages/provider-disponibilities'
    | '/pilotages/provider-service-categories'
    | '/pilotages/providers'
    | '/pilotages/request-type-delays'
    | '/pilotages/request-type-service-categories'
    | '/pilotages/request-types'
    | '/pilotages/requisition-types'
    | '/pilotages/sectors'
    | '/pilotages/service-categories'
    | '/pilotages/services'
    | '/pilotages/subdivision-clients'
    | '/pilotages/teams'
    | '/pilotages/test-table'
    | '/pilotages/users'
    | '/administrations/roles/update/$id'
    | '/pilotages/clients/update/$id'
    | '/pilotages/conformity-types/update/$id'
    | '/pilotages/delay-types/update/$id'
    | '/pilotages/deliverables/update/$id'
    | '/pilotages/flows/update/$id'
    | '/pilotages/holidays/update/$id'
    | '/pilotages/provider-disponibilities/update/$id'
    | '/pilotages/provider-service-categories/update/$id'
    | '/pilotages/providers/update/$id'
    | '/pilotages/request-type-delays/update/$id'
    | '/pilotages/request-type-service-categories/update/$id'
    | '/pilotages/request-types/update/$id'
    | '/pilotages/requisition-types/update/$id'
    | '/pilotages/sectors/update/$id'
    | '/pilotages/service-categories/update/$id'
    | '/pilotages/services/update/$id'
    | '/pilotages/subdivision-clients/update/$id'
    | '/pilotages/teams/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/unauthorized'
    | '/'
    | '/login'
    | '/verify-email/$token'
    | '/profile'
    | '/administrations/roles/create'
    | '/pilotages/clients/create'
    | '/pilotages/conformity-types/create'
    | '/pilotages/delay-types/create'
    | '/pilotages/deliverables/create'
    | '/pilotages/flows/create'
    | '/pilotages/holidays/create'
    | '/pilotages/provider-disponibilities/create'
    | '/pilotages/provider-service-categories/create'
    | '/pilotages/providers/create'
    | '/pilotages/request-type-delays/create'
    | '/pilotages/request-type-service-categories/create'
    | '/pilotages/request-types/create'
    | '/pilotages/requisition-types/create'
    | '/pilotages/sectors/create'
    | '/pilotages/service-categories/create'
    | '/pilotages/services/create'
    | '/pilotages/subdivision-clients/create'
    | '/pilotages/teams/create'
    | '/pilotages/users/create'
    | '/administrations/roles'
    | '/pilotages/clients'
    | '/pilotages/conformity-types'
    | '/pilotages/delay-types'
    | '/pilotages/deliverable-delay-flows'
    | '/pilotages/deliverable-delay-request-types'
    | '/pilotages/deliverables'
    | '/pilotages/flows'
    | '/pilotages/holidays'
    | '/pilotages/provider-disponibilities'
    | '/pilotages/provider-service-categories'
    | '/pilotages/providers'
    | '/pilotages/request-type-delays'
    | '/pilotages/request-type-service-categories'
    | '/pilotages/request-types'
    | '/pilotages/requisition-types'
    | '/pilotages/sectors'
    | '/pilotages/service-categories'
    | '/pilotages/services'
    | '/pilotages/subdivision-clients'
    | '/pilotages/teams'
    | '/pilotages/test-table'
    | '/pilotages/users'
    | '/administrations/roles/update/$id'
    | '/pilotages/clients/update/$id'
    | '/pilotages/conformity-types/update/$id'
    | '/pilotages/delay-types/update/$id'
    | '/pilotages/deliverables/update/$id'
    | '/pilotages/flows/update/$id'
    | '/pilotages/holidays/update/$id'
    | '/pilotages/provider-disponibilities/update/$id'
    | '/pilotages/provider-service-categories/update/$id'
    | '/pilotages/providers/update/$id'
    | '/pilotages/request-type-delays/update/$id'
    | '/pilotages/request-type-service-categories/update/$id'
    | '/pilotages/request-types/update/$id'
    | '/pilotages/requisition-types/update/$id'
    | '/pilotages/sectors/update/$id'
    | '/pilotages/service-categories/update/$id'
    | '/pilotages/services/update/$id'
    | '/pilotages/subdivision-clients/update/$id'
    | '/pilotages/teams/update/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/unauthorized'
    | '/_authenticated/'
    | '/_guest/(login)/login'
    | '/_guest/verify-email/$token'
    | '/_authenticated/profile/'
    | '/_authenticated/administrations/roles/create'
    | '/_authenticated/pilotages/clients/create'
    | '/_authenticated/pilotages/conformity-types/create'
    | '/_authenticated/pilotages/delay-types/create'
    | '/_authenticated/pilotages/deliverables/create'
    | '/_authenticated/pilotages/flows/create'
    | '/_authenticated/pilotages/holidays/create'
    | '/_authenticated/pilotages/provider-disponibilities/create'
    | '/_authenticated/pilotages/provider-service-categories/create'
    | '/_authenticated/pilotages/providers/create'
    | '/_authenticated/pilotages/request-type-delays/create'
    | '/_authenticated/pilotages/request-type-service-categories/create'
    | '/_authenticated/pilotages/request-types/create'
    | '/_authenticated/pilotages/requisition-types/create'
    | '/_authenticated/pilotages/sectors/create'
    | '/_authenticated/pilotages/service-categories/create'
    | '/_authenticated/pilotages/services/create'
    | '/_authenticated/pilotages/subdivision-clients/create'
    | '/_authenticated/pilotages/teams/create'
    | '/_authenticated/pilotages/users/create'
    | '/_authenticated/administrations/roles/'
    | '/_authenticated/pilotages/clients/'
    | '/_authenticated/pilotages/conformity-types/'
    | '/_authenticated/pilotages/delay-types/'
    | '/_authenticated/pilotages/deliverable-delay-flows/'
    | '/_authenticated/pilotages/deliverable-delay-request-types/'
    | '/_authenticated/pilotages/deliverables/'
    | '/_authenticated/pilotages/flows/'
    | '/_authenticated/pilotages/holidays/'
    | '/_authenticated/pilotages/provider-disponibilities/'
    | '/_authenticated/pilotages/provider-service-categories/'
    | '/_authenticated/pilotages/providers/'
    | '/_authenticated/pilotages/request-type-delays/'
    | '/_authenticated/pilotages/request-type-service-categories/'
    | '/_authenticated/pilotages/request-types/'
    | '/_authenticated/pilotages/requisition-types/'
    | '/_authenticated/pilotages/sectors/'
    | '/_authenticated/pilotages/service-categories/'
    | '/_authenticated/pilotages/services/'
    | '/_authenticated/pilotages/subdivision-clients/'
    | '/_authenticated/pilotages/teams/'
    | '/_authenticated/pilotages/test-table/'
    | '/_authenticated/pilotages/users/'
    | '/_authenticated/administrations/roles/update/$id'
    | '/_authenticated/pilotages/clients/update/$id'
    | '/_authenticated/pilotages/conformity-types/update/$id'
    | '/_authenticated/pilotages/delay-types/update/$id'
    | '/_authenticated/pilotages/deliverables/update/$id'
    | '/_authenticated/pilotages/flows/update/$id'
    | '/_authenticated/pilotages/holidays/update/$id'
    | '/_authenticated/pilotages/provider-disponibilities/update/$id'
    | '/_authenticated/pilotages/provider-service-categories/update/$id'
    | '/_authenticated/pilotages/providers/update/$id'
    | '/_authenticated/pilotages/request-type-delays/update/$id'
    | '/_authenticated/pilotages/request-type-service-categories/update/$id'
    | '/_authenticated/pilotages/request-types/update/$id'
    | '/_authenticated/pilotages/requisition-types/update/$id'
    | '/_authenticated/pilotages/sectors/update/$id'
    | '/_authenticated/pilotages/service-categories/update/$id'
    | '/_authenticated/pilotages/services/update/$id'
    | '/_authenticated/pilotages/subdivision-clients/update/$id'
    | '/_authenticated/pilotages/teams/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/verify-email/$token': {
      id: '/_guest/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof GuestVerifyEmailTokenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/(login)/login': {
      id: '/_guest/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestloginLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/pilotages/users/': {
      id: '/_authenticated/pilotages/users/'
      path: '/pilotages/users'
      fullPath: '/pilotages/users'
      preLoaderRoute: typeof AuthenticatedPilotagesUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/test-table/': {
      id: '/_authenticated/pilotages/test-table/'
      path: '/pilotages/test-table'
      fullPath: '/pilotages/test-table'
      preLoaderRoute: typeof AuthenticatedPilotagesTestTableIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/teams/': {
      id: '/_authenticated/pilotages/teams/'
      path: '/pilotages/teams'
      fullPath: '/pilotages/teams'
      preLoaderRoute: typeof AuthenticatedPilotagesTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/subdivision-clients/': {
      id: '/_authenticated/pilotages/subdivision-clients/'
      path: '/pilotages/subdivision-clients'
      fullPath: '/pilotages/subdivision-clients'
      preLoaderRoute: typeof AuthenticatedPilotagesSubdivisionClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/services/': {
      id: '/_authenticated/pilotages/services/'
      path: '/pilotages/services'
      fullPath: '/pilotages/services'
      preLoaderRoute: typeof AuthenticatedPilotagesServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/service-categories/': {
      id: '/_authenticated/pilotages/service-categories/'
      path: '/pilotages/service-categories'
      fullPath: '/pilotages/service-categories'
      preLoaderRoute: typeof AuthenticatedPilotagesServiceCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/sectors/': {
      id: '/_authenticated/pilotages/sectors/'
      path: '/pilotages/sectors'
      fullPath: '/pilotages/sectors'
      preLoaderRoute: typeof AuthenticatedPilotagesSectorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/requisition-types/': {
      id: '/_authenticated/pilotages/requisition-types/'
      path: '/pilotages/requisition-types'
      fullPath: '/pilotages/requisition-types'
      preLoaderRoute: typeof AuthenticatedPilotagesRequisitionTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-types/': {
      id: '/_authenticated/pilotages/request-types/'
      path: '/pilotages/request-types'
      fullPath: '/pilotages/request-types'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-type-service-categories/': {
      id: '/_authenticated/pilotages/request-type-service-categories/'
      path: '/pilotages/request-type-service-categories'
      fullPath: '/pilotages/request-type-service-categories'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-type-delays/': {
      id: '/_authenticated/pilotages/request-type-delays/'
      path: '/pilotages/request-type-delays'
      fullPath: '/pilotages/request-type-delays'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypeDelaysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/providers/': {
      id: '/_authenticated/pilotages/providers/'
      path: '/pilotages/providers'
      fullPath: '/pilotages/providers'
      preLoaderRoute: typeof AuthenticatedPilotagesProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/provider-service-categories/': {
      id: '/_authenticated/pilotages/provider-service-categories/'
      path: '/pilotages/provider-service-categories'
      fullPath: '/pilotages/provider-service-categories'
      preLoaderRoute: typeof AuthenticatedPilotagesProviderServiceCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/provider-disponibilities/': {
      id: '/_authenticated/pilotages/provider-disponibilities/'
      path: '/pilotages/provider-disponibilities'
      fullPath: '/pilotages/provider-disponibilities'
      preLoaderRoute: typeof AuthenticatedPilotagesProviderDisponibilitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/holidays/': {
      id: '/_authenticated/pilotages/holidays/'
      path: '/pilotages/holidays'
      fullPath: '/pilotages/holidays'
      preLoaderRoute: typeof AuthenticatedPilotagesHolidaysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/flows/': {
      id: '/_authenticated/pilotages/flows/'
      path: '/pilotages/flows'
      fullPath: '/pilotages/flows'
      preLoaderRoute: typeof AuthenticatedPilotagesFlowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/deliverables/': {
      id: '/_authenticated/pilotages/deliverables/'
      path: '/pilotages/deliverables'
      fullPath: '/pilotages/deliverables'
      preLoaderRoute: typeof AuthenticatedPilotagesDeliverablesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/deliverable-delay-request-types/': {
      id: '/_authenticated/pilotages/deliverable-delay-request-types/'
      path: '/pilotages/deliverable-delay-request-types'
      fullPath: '/pilotages/deliverable-delay-request-types'
      preLoaderRoute: typeof AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/deliverable-delay-flows/': {
      id: '/_authenticated/pilotages/deliverable-delay-flows/'
      path: '/pilotages/deliverable-delay-flows'
      fullPath: '/pilotages/deliverable-delay-flows'
      preLoaderRoute: typeof AuthenticatedPilotagesDeliverableDelayFlowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/delay-types/': {
      id: '/_authenticated/pilotages/delay-types/'
      path: '/pilotages/delay-types'
      fullPath: '/pilotages/delay-types'
      preLoaderRoute: typeof AuthenticatedPilotagesDelayTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/conformity-types/': {
      id: '/_authenticated/pilotages/conformity-types/'
      path: '/pilotages/conformity-types'
      fullPath: '/pilotages/conformity-types'
      preLoaderRoute: typeof AuthenticatedPilotagesConformityTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/clients/': {
      id: '/_authenticated/pilotages/clients/'
      path: '/pilotages/clients'
      fullPath: '/pilotages/clients'
      preLoaderRoute: typeof AuthenticatedPilotagesClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administrations/roles/': {
      id: '/_authenticated/administrations/roles/'
      path: '/administrations/roles'
      fullPath: '/administrations/roles'
      preLoaderRoute: typeof AuthenticatedAdministrationsRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/users/create': {
      id: '/_authenticated/pilotages/users/create'
      path: '/pilotages/users/create'
      fullPath: '/pilotages/users/create'
      preLoaderRoute: typeof AuthenticatedPilotagesUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/teams/create': {
      id: '/_authenticated/pilotages/teams/create'
      path: '/pilotages/teams/create'
      fullPath: '/pilotages/teams/create'
      preLoaderRoute: typeof AuthenticatedPilotagesTeamsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/subdivision-clients/create': {
      id: '/_authenticated/pilotages/subdivision-clients/create'
      path: '/pilotages/subdivision-clients/create'
      fullPath: '/pilotages/subdivision-clients/create'
      preLoaderRoute: typeof AuthenticatedPilotagesSubdivisionClientsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/services/create': {
      id: '/_authenticated/pilotages/services/create'
      path: '/pilotages/services/create'
      fullPath: '/pilotages/services/create'
      preLoaderRoute: typeof AuthenticatedPilotagesServicesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/service-categories/create': {
      id: '/_authenticated/pilotages/service-categories/create'
      path: '/pilotages/service-categories/create'
      fullPath: '/pilotages/service-categories/create'
      preLoaderRoute: typeof AuthenticatedPilotagesServiceCategoriesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/sectors/create': {
      id: '/_authenticated/pilotages/sectors/create'
      path: '/pilotages/sectors/create'
      fullPath: '/pilotages/sectors/create'
      preLoaderRoute: typeof AuthenticatedPilotagesSectorsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/requisition-types/create': {
      id: '/_authenticated/pilotages/requisition-types/create'
      path: '/pilotages/requisition-types/create'
      fullPath: '/pilotages/requisition-types/create'
      preLoaderRoute: typeof AuthenticatedPilotagesRequisitionTypesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-types/create': {
      id: '/_authenticated/pilotages/request-types/create'
      path: '/pilotages/request-types/create'
      fullPath: '/pilotages/request-types/create'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-type-service-categories/create': {
      id: '/_authenticated/pilotages/request-type-service-categories/create'
      path: '/pilotages/request-type-service-categories/create'
      fullPath: '/pilotages/request-type-service-categories/create'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-type-delays/create': {
      id: '/_authenticated/pilotages/request-type-delays/create'
      path: '/pilotages/request-type-delays/create'
      fullPath: '/pilotages/request-type-delays/create'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypeDelaysCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/providers/create': {
      id: '/_authenticated/pilotages/providers/create'
      path: '/pilotages/providers/create'
      fullPath: '/pilotages/providers/create'
      preLoaderRoute: typeof AuthenticatedPilotagesProvidersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/provider-service-categories/create': {
      id: '/_authenticated/pilotages/provider-service-categories/create'
      path: '/pilotages/provider-service-categories/create'
      fullPath: '/pilotages/provider-service-categories/create'
      preLoaderRoute: typeof AuthenticatedPilotagesProviderServiceCategoriesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/provider-disponibilities/create': {
      id: '/_authenticated/pilotages/provider-disponibilities/create'
      path: '/pilotages/provider-disponibilities/create'
      fullPath: '/pilotages/provider-disponibilities/create'
      preLoaderRoute: typeof AuthenticatedPilotagesProviderDisponibilitiesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/holidays/create': {
      id: '/_authenticated/pilotages/holidays/create'
      path: '/pilotages/holidays/create'
      fullPath: '/pilotages/holidays/create'
      preLoaderRoute: typeof AuthenticatedPilotagesHolidaysCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/flows/create': {
      id: '/_authenticated/pilotages/flows/create'
      path: '/pilotages/flows/create'
      fullPath: '/pilotages/flows/create'
      preLoaderRoute: typeof AuthenticatedPilotagesFlowsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/deliverables/create': {
      id: '/_authenticated/pilotages/deliverables/create'
      path: '/pilotages/deliverables/create'
      fullPath: '/pilotages/deliverables/create'
      preLoaderRoute: typeof AuthenticatedPilotagesDeliverablesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/delay-types/create': {
      id: '/_authenticated/pilotages/delay-types/create'
      path: '/pilotages/delay-types/create'
      fullPath: '/pilotages/delay-types/create'
      preLoaderRoute: typeof AuthenticatedPilotagesDelayTypesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/conformity-types/create': {
      id: '/_authenticated/pilotages/conformity-types/create'
      path: '/pilotages/conformity-types/create'
      fullPath: '/pilotages/conformity-types/create'
      preLoaderRoute: typeof AuthenticatedPilotagesConformityTypesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/clients/create': {
      id: '/_authenticated/pilotages/clients/create'
      path: '/pilotages/clients/create'
      fullPath: '/pilotages/clients/create'
      preLoaderRoute: typeof AuthenticatedPilotagesClientsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administrations/roles/create': {
      id: '/_authenticated/administrations/roles/create'
      path: '/administrations/roles/create'
      fullPath: '/administrations/roles/create'
      preLoaderRoute: typeof AuthenticatedAdministrationsRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/teams/update/$id': {
      id: '/_authenticated/pilotages/teams/update/$id'
      path: '/pilotages/teams/update/$id'
      fullPath: '/pilotages/teams/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesTeamsUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/subdivision-clients/update/$id': {
      id: '/_authenticated/pilotages/subdivision-clients/update/$id'
      path: '/pilotages/subdivision-clients/update/$id'
      fullPath: '/pilotages/subdivision-clients/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesSubdivisionClientsUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/services/update/$id': {
      id: '/_authenticated/pilotages/services/update/$id'
      path: '/pilotages/services/update/$id'
      fullPath: '/pilotages/services/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesServicesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/service-categories/update/$id': {
      id: '/_authenticated/pilotages/service-categories/update/$id'
      path: '/pilotages/service-categories/update/$id'
      fullPath: '/pilotages/service-categories/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesServiceCategoriesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/sectors/update/$id': {
      id: '/_authenticated/pilotages/sectors/update/$id'
      path: '/pilotages/sectors/update/$id'
      fullPath: '/pilotages/sectors/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesSectorsUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/requisition-types/update/$id': {
      id: '/_authenticated/pilotages/requisition-types/update/$id'
      path: '/pilotages/requisition-types/update/$id'
      fullPath: '/pilotages/requisition-types/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesRequisitionTypesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-types/update/$id': {
      id: '/_authenticated/pilotages/request-types/update/$id'
      path: '/pilotages/request-types/update/$id'
      fullPath: '/pilotages/request-types/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-type-service-categories/update/$id': {
      id: '/_authenticated/pilotages/request-type-service-categories/update/$id'
      path: '/pilotages/request-type-service-categories/update/$id'
      fullPath: '/pilotages/request-type-service-categories/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/request-type-delays/update/$id': {
      id: '/_authenticated/pilotages/request-type-delays/update/$id'
      path: '/pilotages/request-type-delays/update/$id'
      fullPath: '/pilotages/request-type-delays/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesRequestTypeDelaysUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/providers/update/$id': {
      id: '/_authenticated/pilotages/providers/update/$id'
      path: '/pilotages/providers/update/$id'
      fullPath: '/pilotages/providers/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesProvidersUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/provider-service-categories/update/$id': {
      id: '/_authenticated/pilotages/provider-service-categories/update/$id'
      path: '/pilotages/provider-service-categories/update/$id'
      fullPath: '/pilotages/provider-service-categories/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/provider-disponibilities/update/$id': {
      id: '/_authenticated/pilotages/provider-disponibilities/update/$id'
      path: '/pilotages/provider-disponibilities/update/$id'
      fullPath: '/pilotages/provider-disponibilities/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/holidays/update/$id': {
      id: '/_authenticated/pilotages/holidays/update/$id'
      path: '/pilotages/holidays/update/$id'
      fullPath: '/pilotages/holidays/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesHolidaysUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/flows/update/$id': {
      id: '/_authenticated/pilotages/flows/update/$id'
      path: '/pilotages/flows/update/$id'
      fullPath: '/pilotages/flows/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesFlowsUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/deliverables/update/$id': {
      id: '/_authenticated/pilotages/deliverables/update/$id'
      path: '/pilotages/deliverables/update/$id'
      fullPath: '/pilotages/deliverables/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesDeliverablesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/delay-types/update/$id': {
      id: '/_authenticated/pilotages/delay-types/update/$id'
      path: '/pilotages/delay-types/update/$id'
      fullPath: '/pilotages/delay-types/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesDelayTypesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/conformity-types/update/$id': {
      id: '/_authenticated/pilotages/conformity-types/update/$id'
      path: '/pilotages/conformity-types/update/$id'
      fullPath: '/pilotages/conformity-types/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesConformityTypesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotages/clients/update/$id': {
      id: '/_authenticated/pilotages/clients/update/$id'
      path: '/pilotages/clients/update/$id'
      fullPath: '/pilotages/clients/update/$id'
      preLoaderRoute: typeof AuthenticatedPilotagesClientsUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administrations/roles/update/$id': {
      id: '/_authenticated/administrations/roles/update/$id'
      path: '/administrations/roles/update/$id'
      fullPath: '/administrations/roles/update/$id'
      preLoaderRoute: typeof AuthenticatedAdministrationsRolesUpdateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedAdministrationsRolesCreateRoute: typeof AuthenticatedAdministrationsRolesCreateRoute
  AuthenticatedPilotagesClientsCreateRoute: typeof AuthenticatedPilotagesClientsCreateRoute
  AuthenticatedPilotagesConformityTypesCreateRoute: typeof AuthenticatedPilotagesConformityTypesCreateRoute
  AuthenticatedPilotagesDelayTypesCreateRoute: typeof AuthenticatedPilotagesDelayTypesCreateRoute
  AuthenticatedPilotagesDeliverablesCreateRoute: typeof AuthenticatedPilotagesDeliverablesCreateRoute
  AuthenticatedPilotagesFlowsCreateRoute: typeof AuthenticatedPilotagesFlowsCreateRoute
  AuthenticatedPilotagesHolidaysCreateRoute: typeof AuthenticatedPilotagesHolidaysCreateRoute
  AuthenticatedPilotagesProviderDisponibilitiesCreateRoute: typeof AuthenticatedPilotagesProviderDisponibilitiesCreateRoute
  AuthenticatedPilotagesProviderServiceCategoriesCreateRoute: typeof AuthenticatedPilotagesProviderServiceCategoriesCreateRoute
  AuthenticatedPilotagesProvidersCreateRoute: typeof AuthenticatedPilotagesProvidersCreateRoute
  AuthenticatedPilotagesRequestTypeDelaysCreateRoute: typeof AuthenticatedPilotagesRequestTypeDelaysCreateRoute
  AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute: typeof AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute
  AuthenticatedPilotagesRequestTypesCreateRoute: typeof AuthenticatedPilotagesRequestTypesCreateRoute
  AuthenticatedPilotagesRequisitionTypesCreateRoute: typeof AuthenticatedPilotagesRequisitionTypesCreateRoute
  AuthenticatedPilotagesSectorsCreateRoute: typeof AuthenticatedPilotagesSectorsCreateRoute
  AuthenticatedPilotagesServiceCategoriesCreateRoute: typeof AuthenticatedPilotagesServiceCategoriesCreateRoute
  AuthenticatedPilotagesServicesCreateRoute: typeof AuthenticatedPilotagesServicesCreateRoute
  AuthenticatedPilotagesSubdivisionClientsCreateRoute: typeof AuthenticatedPilotagesSubdivisionClientsCreateRoute
  AuthenticatedPilotagesTeamsCreateRoute: typeof AuthenticatedPilotagesTeamsCreateRoute
  AuthenticatedPilotagesUsersCreateRoute: typeof AuthenticatedPilotagesUsersCreateRoute
  AuthenticatedAdministrationsRolesIndexRoute: typeof AuthenticatedAdministrationsRolesIndexRoute
  AuthenticatedPilotagesClientsIndexRoute: typeof AuthenticatedPilotagesClientsIndexRoute
  AuthenticatedPilotagesConformityTypesIndexRoute: typeof AuthenticatedPilotagesConformityTypesIndexRoute
  AuthenticatedPilotagesDelayTypesIndexRoute: typeof AuthenticatedPilotagesDelayTypesIndexRoute
  AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute: typeof AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute
  AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute: typeof AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute
  AuthenticatedPilotagesDeliverablesIndexRoute: typeof AuthenticatedPilotagesDeliverablesIndexRoute
  AuthenticatedPilotagesFlowsIndexRoute: typeof AuthenticatedPilotagesFlowsIndexRoute
  AuthenticatedPilotagesHolidaysIndexRoute: typeof AuthenticatedPilotagesHolidaysIndexRoute
  AuthenticatedPilotagesProviderDisponibilitiesIndexRoute: typeof AuthenticatedPilotagesProviderDisponibilitiesIndexRoute
  AuthenticatedPilotagesProviderServiceCategoriesIndexRoute: typeof AuthenticatedPilotagesProviderServiceCategoriesIndexRoute
  AuthenticatedPilotagesProvidersIndexRoute: typeof AuthenticatedPilotagesProvidersIndexRoute
  AuthenticatedPilotagesRequestTypeDelaysIndexRoute: typeof AuthenticatedPilotagesRequestTypeDelaysIndexRoute
  AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute: typeof AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute
  AuthenticatedPilotagesRequestTypesIndexRoute: typeof AuthenticatedPilotagesRequestTypesIndexRoute
  AuthenticatedPilotagesRequisitionTypesIndexRoute: typeof AuthenticatedPilotagesRequisitionTypesIndexRoute
  AuthenticatedPilotagesSectorsIndexRoute: typeof AuthenticatedPilotagesSectorsIndexRoute
  AuthenticatedPilotagesServiceCategoriesIndexRoute: typeof AuthenticatedPilotagesServiceCategoriesIndexRoute
  AuthenticatedPilotagesServicesIndexRoute: typeof AuthenticatedPilotagesServicesIndexRoute
  AuthenticatedPilotagesSubdivisionClientsIndexRoute: typeof AuthenticatedPilotagesSubdivisionClientsIndexRoute
  AuthenticatedPilotagesTeamsIndexRoute: typeof AuthenticatedPilotagesTeamsIndexRoute
  AuthenticatedPilotagesTestTableIndexRoute: typeof AuthenticatedPilotagesTestTableIndexRoute
  AuthenticatedPilotagesUsersIndexRoute: typeof AuthenticatedPilotagesUsersIndexRoute
  AuthenticatedAdministrationsRolesUpdateIdRoute: typeof AuthenticatedAdministrationsRolesUpdateIdRoute
  AuthenticatedPilotagesClientsUpdateIdRoute: typeof AuthenticatedPilotagesClientsUpdateIdRoute
  AuthenticatedPilotagesConformityTypesUpdateIdRoute: typeof AuthenticatedPilotagesConformityTypesUpdateIdRoute
  AuthenticatedPilotagesDelayTypesUpdateIdRoute: typeof AuthenticatedPilotagesDelayTypesUpdateIdRoute
  AuthenticatedPilotagesDeliverablesUpdateIdRoute: typeof AuthenticatedPilotagesDeliverablesUpdateIdRoute
  AuthenticatedPilotagesFlowsUpdateIdRoute: typeof AuthenticatedPilotagesFlowsUpdateIdRoute
  AuthenticatedPilotagesHolidaysUpdateIdRoute: typeof AuthenticatedPilotagesHolidaysUpdateIdRoute
  AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute: typeof AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute
  AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute: typeof AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute
  AuthenticatedPilotagesProvidersUpdateIdRoute: typeof AuthenticatedPilotagesProvidersUpdateIdRoute
  AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute: typeof AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute
  AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute: typeof AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute
  AuthenticatedPilotagesRequestTypesUpdateIdRoute: typeof AuthenticatedPilotagesRequestTypesUpdateIdRoute
  AuthenticatedPilotagesRequisitionTypesUpdateIdRoute: typeof AuthenticatedPilotagesRequisitionTypesUpdateIdRoute
  AuthenticatedPilotagesSectorsUpdateIdRoute: typeof AuthenticatedPilotagesSectorsUpdateIdRoute
  AuthenticatedPilotagesServiceCategoriesUpdateIdRoute: typeof AuthenticatedPilotagesServiceCategoriesUpdateIdRoute
  AuthenticatedPilotagesServicesUpdateIdRoute: typeof AuthenticatedPilotagesServicesUpdateIdRoute
  AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute: typeof AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute
  AuthenticatedPilotagesTeamsUpdateIdRoute: typeof AuthenticatedPilotagesTeamsUpdateIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedAdministrationsRolesCreateRoute:
    AuthenticatedAdministrationsRolesCreateRoute,
  AuthenticatedPilotagesClientsCreateRoute:
    AuthenticatedPilotagesClientsCreateRoute,
  AuthenticatedPilotagesConformityTypesCreateRoute:
    AuthenticatedPilotagesConformityTypesCreateRoute,
  AuthenticatedPilotagesDelayTypesCreateRoute:
    AuthenticatedPilotagesDelayTypesCreateRoute,
  AuthenticatedPilotagesDeliverablesCreateRoute:
    AuthenticatedPilotagesDeliverablesCreateRoute,
  AuthenticatedPilotagesFlowsCreateRoute:
    AuthenticatedPilotagesFlowsCreateRoute,
  AuthenticatedPilotagesHolidaysCreateRoute:
    AuthenticatedPilotagesHolidaysCreateRoute,
  AuthenticatedPilotagesProviderDisponibilitiesCreateRoute:
    AuthenticatedPilotagesProviderDisponibilitiesCreateRoute,
  AuthenticatedPilotagesProviderServiceCategoriesCreateRoute:
    AuthenticatedPilotagesProviderServiceCategoriesCreateRoute,
  AuthenticatedPilotagesProvidersCreateRoute:
    AuthenticatedPilotagesProvidersCreateRoute,
  AuthenticatedPilotagesRequestTypeDelaysCreateRoute:
    AuthenticatedPilotagesRequestTypeDelaysCreateRoute,
  AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute:
    AuthenticatedPilotagesRequestTypeServiceCategoriesCreateRoute,
  AuthenticatedPilotagesRequestTypesCreateRoute:
    AuthenticatedPilotagesRequestTypesCreateRoute,
  AuthenticatedPilotagesRequisitionTypesCreateRoute:
    AuthenticatedPilotagesRequisitionTypesCreateRoute,
  AuthenticatedPilotagesSectorsCreateRoute:
    AuthenticatedPilotagesSectorsCreateRoute,
  AuthenticatedPilotagesServiceCategoriesCreateRoute:
    AuthenticatedPilotagesServiceCategoriesCreateRoute,
  AuthenticatedPilotagesServicesCreateRoute:
    AuthenticatedPilotagesServicesCreateRoute,
  AuthenticatedPilotagesSubdivisionClientsCreateRoute:
    AuthenticatedPilotagesSubdivisionClientsCreateRoute,
  AuthenticatedPilotagesTeamsCreateRoute:
    AuthenticatedPilotagesTeamsCreateRoute,
  AuthenticatedPilotagesUsersCreateRoute:
    AuthenticatedPilotagesUsersCreateRoute,
  AuthenticatedAdministrationsRolesIndexRoute:
    AuthenticatedAdministrationsRolesIndexRoute,
  AuthenticatedPilotagesClientsIndexRoute:
    AuthenticatedPilotagesClientsIndexRoute,
  AuthenticatedPilotagesConformityTypesIndexRoute:
    AuthenticatedPilotagesConformityTypesIndexRoute,
  AuthenticatedPilotagesDelayTypesIndexRoute:
    AuthenticatedPilotagesDelayTypesIndexRoute,
  AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute:
    AuthenticatedPilotagesDeliverableDelayFlowsIndexRoute,
  AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute:
    AuthenticatedPilotagesDeliverableDelayRequestTypesIndexRoute,
  AuthenticatedPilotagesDeliverablesIndexRoute:
    AuthenticatedPilotagesDeliverablesIndexRoute,
  AuthenticatedPilotagesFlowsIndexRoute: AuthenticatedPilotagesFlowsIndexRoute,
  AuthenticatedPilotagesHolidaysIndexRoute:
    AuthenticatedPilotagesHolidaysIndexRoute,
  AuthenticatedPilotagesProviderDisponibilitiesIndexRoute:
    AuthenticatedPilotagesProviderDisponibilitiesIndexRoute,
  AuthenticatedPilotagesProviderServiceCategoriesIndexRoute:
    AuthenticatedPilotagesProviderServiceCategoriesIndexRoute,
  AuthenticatedPilotagesProvidersIndexRoute:
    AuthenticatedPilotagesProvidersIndexRoute,
  AuthenticatedPilotagesRequestTypeDelaysIndexRoute:
    AuthenticatedPilotagesRequestTypeDelaysIndexRoute,
  AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute:
    AuthenticatedPilotagesRequestTypeServiceCategoriesIndexRoute,
  AuthenticatedPilotagesRequestTypesIndexRoute:
    AuthenticatedPilotagesRequestTypesIndexRoute,
  AuthenticatedPilotagesRequisitionTypesIndexRoute:
    AuthenticatedPilotagesRequisitionTypesIndexRoute,
  AuthenticatedPilotagesSectorsIndexRoute:
    AuthenticatedPilotagesSectorsIndexRoute,
  AuthenticatedPilotagesServiceCategoriesIndexRoute:
    AuthenticatedPilotagesServiceCategoriesIndexRoute,
  AuthenticatedPilotagesServicesIndexRoute:
    AuthenticatedPilotagesServicesIndexRoute,
  AuthenticatedPilotagesSubdivisionClientsIndexRoute:
    AuthenticatedPilotagesSubdivisionClientsIndexRoute,
  AuthenticatedPilotagesTeamsIndexRoute: AuthenticatedPilotagesTeamsIndexRoute,
  AuthenticatedPilotagesTestTableIndexRoute:
    AuthenticatedPilotagesTestTableIndexRoute,
  AuthenticatedPilotagesUsersIndexRoute: AuthenticatedPilotagesUsersIndexRoute,
  AuthenticatedAdministrationsRolesUpdateIdRoute:
    AuthenticatedAdministrationsRolesUpdateIdRoute,
  AuthenticatedPilotagesClientsUpdateIdRoute:
    AuthenticatedPilotagesClientsUpdateIdRoute,
  AuthenticatedPilotagesConformityTypesUpdateIdRoute:
    AuthenticatedPilotagesConformityTypesUpdateIdRoute,
  AuthenticatedPilotagesDelayTypesUpdateIdRoute:
    AuthenticatedPilotagesDelayTypesUpdateIdRoute,
  AuthenticatedPilotagesDeliverablesUpdateIdRoute:
    AuthenticatedPilotagesDeliverablesUpdateIdRoute,
  AuthenticatedPilotagesFlowsUpdateIdRoute:
    AuthenticatedPilotagesFlowsUpdateIdRoute,
  AuthenticatedPilotagesHolidaysUpdateIdRoute:
    AuthenticatedPilotagesHolidaysUpdateIdRoute,
  AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute:
    AuthenticatedPilotagesProviderDisponibilitiesUpdateIdRoute,
  AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute:
    AuthenticatedPilotagesProviderServiceCategoriesUpdateIdRoute,
  AuthenticatedPilotagesProvidersUpdateIdRoute:
    AuthenticatedPilotagesProvidersUpdateIdRoute,
  AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute:
    AuthenticatedPilotagesRequestTypeDelaysUpdateIdRoute,
  AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute:
    AuthenticatedPilotagesRequestTypeServiceCategoriesUpdateIdRoute,
  AuthenticatedPilotagesRequestTypesUpdateIdRoute:
    AuthenticatedPilotagesRequestTypesUpdateIdRoute,
  AuthenticatedPilotagesRequisitionTypesUpdateIdRoute:
    AuthenticatedPilotagesRequisitionTypesUpdateIdRoute,
  AuthenticatedPilotagesSectorsUpdateIdRoute:
    AuthenticatedPilotagesSectorsUpdateIdRoute,
  AuthenticatedPilotagesServiceCategoriesUpdateIdRoute:
    AuthenticatedPilotagesServiceCategoriesUpdateIdRoute,
  AuthenticatedPilotagesServicesUpdateIdRoute:
    AuthenticatedPilotagesServicesUpdateIdRoute,
  AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute:
    AuthenticatedPilotagesSubdivisionClientsUpdateIdRoute,
  AuthenticatedPilotagesTeamsUpdateIdRoute:
    AuthenticatedPilotagesTeamsUpdateIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestloginLoginRoute: typeof GuestloginLoginRoute
  GuestVerifyEmailTokenRoute: typeof GuestVerifyEmailTokenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestloginLoginRoute: GuestloginLoginRoute,
  GuestVerifyEmailTokenRoute: GuestVerifyEmailTokenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
